### PR TITLE
chore: release v4.0.0

### PR DESCRIPTION
**Pull request by willopez**
# v.4.0.0

## Refactors

- refactor: Configure `react-testing-library` and remove unnecessary testing dependencies [#686](https://github.com/reactioncommerce/example-storefront/pull/686)

This is a major update that introduces the following refactors in PR [#667](https://github.com/reactioncommerce/example-storefront/pull/667)
- Use React hooks for various parts of the application including orders, cart, shop, translations and more. This refactor remove various HOC that added unnecessary complexity to the app.
- React context is now used and all previous uses of MobX have been removed. Using React context greatly simplifies local states management.
- Simple translation helpers have been added to support multi-lingual shops. See the `useTranslation` React hook for more details.
- Next.js has been update to use version 9.4.1, which includes support for [SSG](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support)(Static Site Generation). By default product pages are re-regenerated every two minutes. Further, various other features, such as dynamic routes and API routes are now used, either a dynamic route or API
as appropriate.
- Various components form the Reaction component library have been removed in favor of using the new Reaction Catalyst design system. This is a stepping stone towards consolidating styling solutions use use only one.

### CODE REVIEW

**Comment by janus-reith** [comment]
~~This needs to be fixed first: https://github.com/reactioncommerce/example-storefront/issues/691~~ ✓

**Comment by janus-reith** [comment]
I wonder if v3.2.0 is a suitable version number, considering all the major changes.

As the decision was made to release the projects independently and not necessarily keep version numbers the same across them, that would be v4.0.0 as the next major.

**Comment by janus-reith** [comment]
As @manueldelreal pointed out, this should probably be merged before a release: https://github.com/reactioncommerce/example-storefront/pull/705

**Comment by balibebas** [comment]
#705 was merged. Is this shippable as is or will there be a new major given the breaking changes to the router with the addition of i18n?

**Comment by ghost** [comment]
I've opened up a few issues which block this realease. I'd also lobby strongly for https://github.com/reactioncommerce/example-storefront/issues/704 before `3.2.0` is released unless there's a beta period of some sort. If that's standard please ignore. I just started looking at this project two days ago.

**Comment by mikemurray** [comment]
@janus-reith Agreed. Bumped to 4.0.0

**Comment by janus-reith** [comment]
Great to hear @mikemurray !

I just noticed that release-next-v3.2.0 doesn't contain all latest commits of trunk, so we should make sure to check this before a release: https://github.com/reactioncommerce/example-storefront/compare/release-next-v3.2.0...trunk

**Comment by janus-reith** [comment]
I'd like to upgrade nextjs to v9.5.1 where all the remaining new features we use are now marked as stable before the release: https://github.com/reactioncommerce/example-storefront/issues/715

**Comment by kieckhafer** [comment]
Closing in favor of #729

**Pull request closed without merging**
