### PR TITLE
fix: runtime build issues

### PR DESCRIPTION
**Pull request by mikemurray**
## Issue

Cannot run app due to regenerator runtime issues

## Solution

Update babel config

## Breaking changes

none

## Testing
1. App should run and be usable

### CODE REVIEW

**Review by willopez — APPROVED** [review]
LGTM

**Comment by janus-reith** [comment]
@mikemurray The babel config I made obsolete for the new version was added back in https://github.com/reactioncommerce/example-storefront/pull/682, introducing this error.
Instead of adjusting the babel config, I'd consider just removing it again.

I don't see us using specific features that would make it reasonable to introduce potential upstream issues by diverging from the nextjs defaults here.

**Comment by willopez** [comment]
@janus-reith just saw your comment, after I approved it. I am open to removing it and simplifying the config. PR welcomed.

**Comment by janus-reith** [comment]
@willopez Yes, I would prefer if we discuss in https://github.com/reactioncommerce/example-storefront/issues/683 or some seperate issue instead how to approach the tests cleanly, and which should be there in general.( I think @HarisSpahija also wanted to contribute to that.)

The previous storefront version also had a bunch of babel dependencies I'd rather not have included here again.

TBH my preference would be to revert https://github.com/reactioncommerce/example-storefront/pull/682 and not merge this one, and fix the tests instead.
Maybe a short term solution could be to have that babel config in a separate test-specific folder? Or any other way to scope it to the tests only, if it actually is necessary.

**Comment by willopez** [comment]
Sounds good, lets discuss on #682

**Comment by willopez** [comment]
This PR removes unnecessary babel config and some dependencies. A new PR will be created to remove snapshot test and related dependencies add react testing library and cypress. See for more context: https://github.com/reactioncommerce/example-storefront/issues/683#issuecomment-644266243

**Pull request merged**
